# Generated by Django 5.1.3 on 2024-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fairyweight', 'Fairyweight (0,150Kg)'), ('antweight', 'Antweight (0,454Kg)'), ('beetleweight', 'Beetleweight (1,360Kg)'), ('hobbyweight', 'Hobbyweight (5,443Kg)'), ('featherweight', 'Featherweight (13,607Kg)'), ('lightweight', 'Lightweight (27,215Kg)'), ('sumo_auto_3kg', 'Sumo Automático (3Kg)'), ('sumo_radio_3kg', 'Sumo Rádio Controlado (3Kg)'), ('sumo_auto_500g', 'Sumo Automático (500g)'), ('sumo_radio_500g', 'Sumo Rádio Controlado (500g)'), ('autonomous', 'Autônomo')], max_length=20)),
                ('trophies', models.IntegerField(default=0, help_text='Número de troféus ganhos')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('retired', 'Aposentado'), ('undefined', 'Indefinido')], default='undefined', max_length=10)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='URL da imagem', max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
