# Generated by Django 5.1.3 on 2024-11-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsRobots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fairyweight', 'Fairyweight (0,150Kg)'), ('antweight', 'Antweight (0,454Kg)'), ('beetleweight', 'Beetleweight (1,360Kg)'), ('hobbyweight', 'Hobbyweight (5,443Kg)'), ('featherweight', 'Featherweight (13,607Kg)'), ('lightweight', 'Lightweight (27,215Kg)'), ('sumo_auto_3kg', 'Sumo Automático (3Kg)'), ('sumo_radio_3kg', 'Sumo Rádio Controlado (3Kg)'), ('sumo_auto_500g', 'Sumo Automático (500g)'), ('sumo_radio_500g', 'Sumo Rádio Controlado (500g)'), ('autonomous', 'Autônomo')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='robots',
            name='category',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='trophies',
        ),
        migrations.AddField(
            model_name='robots',
            name='bronze_trophies',
            field=models.IntegerField(default=0, help_text='Número de troféus de bronze'),
        ),
        migrations.AddField(
            model_name='robots',
            name='gold_trophies',
            field=models.IntegerField(default=0, help_text='Número de troféus de ouro'),
        ),
        migrations.AddField(
            model_name='robots',
            name='silver_trophies',
            field=models.IntegerField(default=0, help_text='Número de troféus de prata'),
        ),
        migrations.AddField(
            model_name='robots',
            name='categories',
            field=models.ManyToManyField(related_name='robots', to='PostsRobots.category'),
        ),
    ]
