# Generated by Django 5.1.3 on 2024-11-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsRobots', '0002_category_remove_robots_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robots',
            name='categories',
        ),
        migrations.AddField(
            model_name='robots',
            name='primary_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_robots', to='PostsRobots.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robots',
            name='secondary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_robots', to='PostsRobots.category'),
        ),
    ]
