# Generated by Django 5.1.3 on 2024-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsRobots', '0003_remove_robots_categories_robots_primary_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robots',
            name='secondary_category',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='primary_category',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='bronze_trophies',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='gold_trophies',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='silver_trophies',
        ),
        migrations.AddField(
            model_name='robots',
            name='category',
            field=models.CharField(choices=[('fairyweight', 'Fairyweight (0,150Kg)'), ('antweight', 'Antweight (0,454Kg)'), ('beetleweight', 'Beetleweight (1,360Kg)'), ('hobbyweight', 'Hobbyweight (5,443Kg)'), ('featherweight', 'Featherweight (13,607Kg)'), ('lightweight', 'Lightweight (27,215Kg)'), ('sumo_auto_3kg', 'Sumo Automático (3Kg)'), ('sumo_radio_3kg', 'Sumo Rádio Controlado (3Kg)'), ('sumo_auto_500g', 'Sumo Automático (500g)'), ('sumo_radio_500g', 'Sumo Rádio Controlado (500g)'), ('autonomous', 'Autônomo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robots',
            name='trophies',
            field=models.IntegerField(default=0, help_text='Número de troféus ganhos'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
