# Generated by Django 5.1.3 on 2024-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsRobots', '0004_remove_robots_secondary_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robots',
            name='trophies',
        ),
        migrations.AddField(
            model_name='robots',
            name='bronze_trophies',
            field=models.IntegerField(default=0, help_text='Número de troféus de bronze'),
        ),
        migrations.AddField(
            model_name='robots',
            name='gold_trophies',
            field=models.IntegerField(default=0, help_text='Número de troféus de ouro'),
        ),
        migrations.AddField(
            model_name='robots',
            name='silver_trophies',
            field=models.IntegerField(default=0, help_text='Número de troféus de prata'),
        ),
    ]
