# Generated by Django 5.1.3 on 2024-11-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsRobots', '0006_posts_delete_robots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='bronze_trophies',
            field=models.IntegerField(default=0, help_text='Number of bronze trophies'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='gold_trophies',
            field=models.IntegerField(default=0, help_text='Number of gold trophies'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='silver_trophies',
            field=models.IntegerField(default=0, help_text='Number of silver trophies'),
        ),
    ]
