# Generated by Django 5.1.3 on 2024-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsRobots', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
    ]
