# Generated by Django 5.1.3 on 2024-11-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsRobots', '0010_remove_comment_author_comment_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='PostsRobots.category'),
        ),
    ]
